// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs).
// git: 8961449 (Mon Jun 10 17:12:43 2024 +0200) [modified]
// Compiled with GHC 9.4.8.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_num_threads(struct futhark_context_config *cfg, int n);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_u32_2d;
struct futhark_u32_2d *futhark_new_u32_2d(struct futhark_context *ctx, const uint32_t *data, int64_t dim0, int64_t dim1);
struct futhark_u32_2d *futhark_new_raw_u32_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
int futhark_values_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr, uint32_t *data);
unsigned char *futhark_values_raw_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
const int64_t *futhark_shape_u32_2d(struct futhark_context *ctx, struct futhark_u32_2d *arr);
struct futhark_u8_1d;
struct futhark_u8_1d *futhark_new_u8_1d(struct futhark_context *ctx, const uint8_t *data, int64_t dim0);
struct futhark_u8_1d *futhark_new_raw_u8_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr);
int futhark_values_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr, uint8_t *data);
unsigned char *futhark_values_raw_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr);
const int64_t *futhark_shape_u8_1d(struct futhark_context *ctx, struct futhark_u8_1d *arr);

// Opaque values
struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9;
struct futhark_opaque_arr_cbezier_1d;
struct futhark_opaque_arr_line_1d;
struct futhark_opaque_arr_text_meta_1d;
struct futhark_opaque_state;
int futhark_free_opaque_6dd49763c6358e312aa409a7c20f36c9(struct futhark_context *ctx, struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 *obj);
int futhark_store_opaque_6dd49763c6358e312aa409a7c20f36c9(struct futhark_context *ctx, const struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 *obj, void **p, size_t *n);
struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 *futhark_restore_opaque_6dd49763c6358e312aa409a7c20f36c9(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_6dd49763c6358e312aa409a7c20f36c9_0(struct futhark_context *ctx, int32_t *out, const struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 *obj);
int futhark_project_opaque_6dd49763c6358e312aa409a7c20f36c9_1(struct futhark_context *ctx, int32_t *out, const struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 *obj);
int futhark_new_opaque_6dd49763c6358e312aa409a7c20f36c9(struct futhark_context *ctx, struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 **out, const int32_t v0, const int32_t v1);
int futhark_free_opaque_arr_cbezier_1d(struct futhark_context *ctx, struct futhark_opaque_arr_cbezier_1d *obj);
int futhark_store_opaque_arr_cbezier_1d(struct futhark_context *ctx, const struct futhark_opaque_arr_cbezier_1d *obj, void **p, size_t *n);
struct futhark_opaque_arr_cbezier_1d *futhark_restore_opaque_arr_cbezier_1d(struct futhark_context *ctx, const void *p);
int futhark_free_opaque_arr_line_1d(struct futhark_context *ctx, struct futhark_opaque_arr_line_1d *obj);
int futhark_store_opaque_arr_line_1d(struct futhark_context *ctx, const struct futhark_opaque_arr_line_1d *obj, void **p, size_t *n);
struct futhark_opaque_arr_line_1d *futhark_restore_opaque_arr_line_1d(struct futhark_context *ctx, const void *p);
int futhark_free_opaque_arr_text_meta_1d(struct futhark_context *ctx, struct futhark_opaque_arr_text_meta_1d *obj);
int futhark_store_opaque_arr_text_meta_1d(struct futhark_context *ctx, const struct futhark_opaque_arr_text_meta_1d *obj, void **p, size_t *n);
struct futhark_opaque_arr_text_meta_1d *futhark_restore_opaque_arr_text_meta_1d(struct futhark_context *ctx, const void *p);
int futhark_free_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state *obj);
int futhark_store_opaque_state(struct futhark_context *ctx, const struct futhark_opaque_state *obj, void **p, size_t *n);
struct futhark_opaque_state *futhark_restore_opaque_state(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_state_h(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_mouse(struct futhark_context *ctx, struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_moving(struct futhark_context *ctx, struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_paused(struct futhark_context *ctx, bool *out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_resolution(struct futhark_context *ctx, int32_t *out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_text_curves(struct futhark_context *ctx, struct futhark_opaque_arr_cbezier_1d **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_text_lines(struct futhark_context *ctx, struct futhark_opaque_arr_line_1d **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_text_meta(struct futhark_context *ctx, struct futhark_opaque_arr_text_meta_1d **out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_time(struct futhark_context *ctx, float *out, const struct futhark_opaque_state *obj);
int futhark_project_opaque_state_w(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_state *obj);
int futhark_new_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state **out, const int64_t f_h, const struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 *f_mouse, const struct futhark_opaque_6dd49763c6358e312aa409a7c20f36c9 *f_moving, const bool f_paused, const int32_t f_resolution, const struct futhark_opaque_arr_cbezier_1d *f_text_curves, const struct futhark_opaque_arr_line_1d *f_text_lines, const struct futhark_opaque_arr_text_meta_1d *f_text_meta, const float f_time, const int64_t f_w);

// Entry points
int futhark_entry_add_text(struct futhark_context *ctx, struct futhark_opaque_state **out0, const struct futhark_opaque_state *in0, const struct futhark_u8_1d *in1, const int32_t in2, const int32_t in3, const int32_t in4);
int futhark_entry_init(struct futhark_context *ctx, struct futhark_opaque_state **out0, const int64_t in0, const int64_t in1);
int futhark_entry_render(struct futhark_context *ctx, struct futhark_u32_2d **out0, const struct futhark_opaque_state *in0);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_multicore
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
